name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  # Prepare environment and build packages
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      
      - run: sudo apt-get install wget unzip
      
      - name: Restore solution
        run: |
          dotnet tool restore
          dotnet restore
          dotnet msbuild -t:FetchDependencies
        
      - name: Setup Netcode Patcher
        id: setup-netcode-patcher
        uses: Lordfirespeed/setup-netcode-patcher@v0.2.0
        with:
          netcode-patcher-version: 2.4.0
          deps-packages: '[{"id": "UnityEngine.Modules", "version": "2022.3.9"}, {"id": "LethalCompany.GameLibs.Steam", "version": "45.0.2-alpha.1"}]'
          deps-paths: '["lib/willis81808-LethalSettings/LethalSettings.dll", "lib/Evaisa-LethalLib/plugins/LethalLib/LethalLib.dll"]'
          target-framework: "netstandard2.1"
      
      - name: Build
        run: dotnet build -p:NETCODE_PATCHER_DIR="${{ steps.setup-netcode-patcher.outputs.netcode-patcher-directory }}"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "dist/*.zip"
